version: "3"
services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    networks:
      - phpnet
    ports:
      - 80:80
      - 443:443

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
    - "3306:3306"
    networks:
      - phpnet
#    volumes:
#      - ./.data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravel
      - MARIADB_DATABASE=laravel
      - MARIADB_ROOT_PASSWORD=laravel
      - TZ=Asia/Taipei

  laravel:
    image: docker.io/bitnami/laravel:10
    container_name: crawler-laravel
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    volumes:
      - './Crawler:/app'
    depends_on:
      - mariadb
    networks:
      - phpnet
    restart: unless-stopped

  chromium:
    image: microbox/chromium-headless
    container_name: chromium
    ports:
      - '9222:9222'
    volumes:
      - /dev/shm:/dev/shm
    command: ["chromium-browser", "--headless", "--disable-gpu", "--remote-debugging-address=127.0.0.1", "--remote-debugging-port=9222", "--no-sandbox"]
    networks:
      - phpnet
    restart: unless-stopped

networks:
  phpnet:
    # external: true
